# dbt/seeds/seed_config.yml
version: 2
seeds:
  - name: bronze_weather
    config:
      column_types:
        time: DateTime
        temp: Float32
        dwpt: Float32
        rhum: Float32  # This is the specific fix
        prcp: Float32
        snow: Float32  # Will handle empty strings as NULL
        wdir: Float32
        wspd: Float32
        wpgt: Float32
        pres: Float32
        tsun: Float32
        coco: Float32
        
  - name: bronze_mobility # Configuration for the second seed
    config:
      column_types:
        timestamp: DateTime
        label: String
        line: String
        Suur-S-Ääsi: Float32
        Suur-S-Lõõtsa: Float32
        Ääsi-Valukoja: Float32
        Lõõtsa-Sepise360: Float32
        Lõõtsa-Valukoja: Float32
        
  - name: bronze_infrared # Configuration for the third seed
    config:
      column_types:
        timestamp: DateTime
        name: String
        out: Int32
        in: Int32